const result=[
    {
    "No":"11",
    "date":"4th December 2021, 19:00 PM",
    "team1":"Spain",
    "team2":"England",
    "img1":"flag/Spain.png",
    "img2":"flag/download.png",
    "team1_prob":"45%",
    "team2_prob":"55%",
    "matches":"15",
    "team1_win":"7",
    'team2_win':"5",
    "draw":"3",
    "team1_top":"David Villa",
    "team2_top":"David Beckham",
    "team1_history":[1,0,1,0,0],
    "team2_history":[0,1,0,1,1],
    "team1_recent":[1,0,1,0,-1],
    "team2_recent":[0,1,0,1,1],

    "team1_player":"Álvaro Morata",
    "team2_player":"Jack Grealish"
},


{
    "No":"12",
    "date":"6th December 2021, 19:00 PM",
    "team1":"Germany",
    "team2":"Brazil",
    "img1":"flag/Germany.png",
    "img2":"flag/Brazil.png",
    "team1_prob":"50%",
    "team2_prob":"50%",
    "matches":"12",
    "team1_win":"5",
    'team2_win':"4",
    "draw":"3",
    "team1_top":"Miroslav Klose",
    "team2_top":"Ronaldinho",
    "team1_history":[1,0,1,0,-1],
    "team2_history":[0,1,0,1,-1],
    "team1_recent":[1,0,1,0,0],
    "team2_recent":[0,1,0,1,1],

    "team1_player":"Kai Havertz",
    "team2_player":"Neymar"
},
{
    "No":"13",
    "date":"7th December 2021, 19:00 PM",
    "team1":"Chile",
    "team2":"France",
    "img1":"flag/Chile.png",
    "img2":"flag/France.png",
    "team1_prob":"20%",
    "team2_prob":"70%",
    "matches":"8",
    "team1_win":"2",
    'team2_win':"5",
    "draw":"1",
    "team1_top":"Alexis Sánchez",
    "team2_top":"Zinedine Zidane",
    "team1_history":[0,0,1,0,-1],
    "team2_history":[1,1,0,1,-1],
    "team1_recent":[1,0,0,0,0],
    "team2_recent":[1,1,-1,1,1],

    "team1_player":"Ben Brereton",
    "team2_player":"Paul Pogba"
},

{
    "No":"14",
    "date":"8th December 2021, 19:00 PM",
    "team1":"Argentina",
    "team2":"England",
    "img1":"flag/Argentina.jpg",
    "img2":"flag/download.png",
    "team1_prob":"50%",
    "team2_prob":"50%",
    "matches":"20",
    "team1_win":"9",
    'team2_win':"9",
    "draw":"2",
    "team1_top":"Lionel Messi",
    "team2_top":"Wayne Rooney",
    "team1_history":[0,0,1,0,-1],
    "team2_history":[1,1,0,1,-1],
    "team1_recent":[1,0,1,0,1],
    "team2_recent":[1,1,-1,0,1],

    "team1_player":"Lionel Messi",
    "team2_player":"Harry Kane"
},

{
    "No":"15",
    "date":"9th December 2021, 19:00 PM",
    "team1":"Spain",
    "team2":"Netherland",
    "img1":"flag/Spain.png",
    "img2":"flag/Netharland.png",
    "team1_prob":"60%",
    "team2_prob":"40%",
    "matches":"17",
    "team1_win":"9",
    'team2_win':"8",
    "draw":"0",
    "team1_top":"Fernando Torres",
    "team2_top":"Faas Wilkes",
    "team1_history":[1,0,1,0,1],
    "team2_history":[0,1,0,1,0],
    "team1_recent":[1,0,1,0,1],
    "team2_recent":[1,1,-1,0,1],

    "team1_player":"Sergio Ramos",
    "team2_player":"Memphis Depay"
},
{
    "No":"16",
    "date":"10th December 2021, 19:00 PM",
    "team1":"Uruguay",
    "team2":"Norway",
    "img1":"flag/Uruguay.png",
    "img2":"flag/Norway.png",
    "team1_prob":"60%",
    "team2_prob":"40%",
    "matches":"7",
    "team1_win":"5",
    'team2_win':"1",
    "draw":"1",
    "team1_top":"Diego Forlán    ",
    "team2_top":"John Arne Riise    ",
    "team1_history":[0,0,0,0,0],
    "team2_history":[1,1,1,1,1],
    "team1_recent":[1,0,1,0,1],
    "team2_recent":[1,1,-1,0,1],

    "team1_player":"Luis Suárez ",
    "team2_player":"Martin Ødegaard"
},
{
    "No":"17",
    "date":"11th December 2021, 19:00 PM",
    "team1":"Italy",
    "team2":"France",
    "img1":"flag/Italy.png",
    "img2":"flag/France.png",
    "team1_prob":"51%",
    "team2_prob":"49%",
    "matches":"21",
    "team1_win":"10",
    'team2_win':"9",
    "draw":"2",
    "team1_top":"Alessandro Del Piero ",
    "team2_top":"Laurent Blanc ",
    "team1_history":[1,1,0,-1,-1],
    "team2_history":[0,0,1,-1,-1],
    "team1_recent":[1,1,1,1,1],
    "team2_recent":[1,1,-1,1,1],

    "team1_player":"Federico Chiesa",
    "team2_player":" Karim Benzema"
},

{
    "No":"18",
    "date":"12th December 2021, 19:00 PM",
    "team1":"Spain",
    "team2":"Brazil",
    "img1":"flag/Spain.png",
    "img2":"flag/Brazil.png",
    "team1_prob":"55%",
    "team2_prob":"45%",
    "matches":"16",
    "team1_win":"8",
    'team2_win':"6",
    "draw":"2",
    "team1_top":"Xavi ",
    "team2_top":"Kaka ",
    "team1_history":[1,1,0,-1,-1],
    "team2_history":[0,0,1,-1,-1],
    "team1_recent":[1,1,1,1,1],
    "team2_recent":[1,1,0,1,1],

    "team1_player":"Sergio Ramos    ",
    "team2_player":"Marcelo Vieira"
},
{
    "No":"19",
    "date":"13th December 2021, 19:00 PM",
    "team1":"Chile",
    "team2":"Argentina",
    "img1":"flag/Chile.png",
    "img2":"flag/Argentina.jpg",
    "team1_prob":"41%",
    "team2_prob":"59%",
    "matches":"16",
    "team1_win":"10",
    'team2_win':"6",
    "draw":"0",
    "team1_top":"Leonel Sanchez  ",
    "team2_top":"Lionel Messi",
    "team1_history":[1,1,0,-1,-1],
    "team2_history":[0,0,1,-1,-1],
    "team1_recent":[1,1,0,0,1],
    "team2_recent":[1,1,0,1,1],

    "team1_player":"Arturo Vidal    ",
    "team2_player":"Paulo Dybala"
},

{
    "No":"20",
    "date":"14th December 2021, 19:00 PM",
    "team1":"Italy",
    "team2":"Norway",
    "img1":"flag/Italy.png",
    "img2":"flag/Norway.png",
    "team1_prob":"80%",
    "team2_prob":"20%",
    "matches":"6",
    "team1_win":"6",
    'team2_win':"0",
    "draw":"0",
    "team1_top":" Alessandro Del Piero",
    "team2_top":"Alexander Sørloth",
    "team1_history":[1,1,1,1,1],
    "team2_history":[0,0,0,0,0],
    "team1_recent":[1,1,1,1,1],
    "team2_recent":[1,1,0,1,0],

    "team1_player":"Ciro Immobile    ",
    "team2_player":"Erling Haaland"
},


{
    "No":"21",
    "date":"15th December 2021, 19:00 PM",
    "team1":"Brazil",
    "team2":"Netherland",
    "img1":"flag/Brazil.png",
    "img2":"flag/Netharland.png",
    "team1_prob":"60%",
    "team2_prob":"40%",
    "matches":"9",
    "team1_win":"6",
    'team2_win':"3",
    "draw":"0",
    "team1_top":" Kaka",
    "team2_top":"Robin van Persie    ",
    "team1_history":[1,1,0,1,0],
    "team2_history":[0,0,1,0,1],
    "team1_recent":[1,1,0,-1,0],
    "team2_recent":[1,1,0,1,1],

    "team1_player":"Neymar    ",
    "team2_player":"Virgil van Dijk    "
},
{
    "No":"22",
    "date":"16th December 2021, 19:00 PM",
    "team1":"Uruguay",
    "team2":"England",
    "img1":"flag/Uruguay.png",
    "img2":"flag/download.png",
    "team1_prob":"55%",
    "team2_prob":"45%",
    "matches":"9",
    "team1_win":"4",
    'team2_win':"4",
    "draw":"1",
    "team1_top":" Frank Lampard    ",
    "team2_top":"Edinson Cavani    ",
    "team1_history":[1,1,0,1,0],
    "team2_history":[0,0,1,0,1],
    "team1_recent":[1,1,0,-1,0],
    "team2_recent":[1,1,0,1,1],

    "team1_player":"Harry Kane",
    "team2_player":" Edinson Cavani  "
},


{
    "No":"23",
    "date":"17th December 2021, 19:00 PM",
    "team1":"Germany",
    "team2":"Italy",
    "img1":"flag/Germany.png",
    "img2":"flag/Italy.png",
    "team1_prob":"49%",
    "team2_prob":"51%",
    "matches":"22",
    "team1_win":"11",
    'team2_win':"10",
    "draw":"1",
    "team1_top":" Miroslav Klose    ",
    "team2_top":"Fabio Cannavaro    ",
    "team1_history":[1,1,0,-1,0],
    "team2_history":[0,0,1,-1,1],
    "team1_recent":[1,1,0,-1,0],
    "team2_recent":[1,1,0,1,1],

    "team1_player":"Thomas Müller    ",
    "team2_player":" Gianluigi Donnarumma  "
},

{
    "No":"24",
    "date":"18th December 2021, 19:00 PM",
    "team1":"Spain",
    "team2":"Argentina",
    "img1":"flag/Spain.png",
    "img2":"flag/Argentina.jpg",
    "team1_prob":"50%",
    "team2_prob":"50%",
    "matches":"10",
    "team1_win":"6",
    'team2_win':"4",
    "draw":"0",
    "team1_top":" Diego Costa    ",
    "team2_top":"Sergio Agüero   ",
    "team1_history":[1,1,0,-1,-1],
    "team2_history":[0,0,1,-1,-1],
    "team1_recent":[1,1,0,-1,0],
    "team2_recent":[1,1,0,1,1],

    "team1_player":"Gerard Moreno    ",
    "team2_player":" Lionel Messi  "
},

{
    "No":"25",
    "date":"19th December 2021, 19:00 PM",
    "team1":"Chile",
    "team2":"France",
    "img1":"flag/Chile.png",
    "img2":"flag/France.png",
    "team1_prob":"20%",
    "team2_prob":"80%",
    "matches":"10",
    "team1_win":"2",
    'team2_win':"7",
    "draw":"1",
    "team1_top":" Alexis Sánchez   ",
    "team2_top":"Zinedine Zidane ",
    "team1_history":[0,0,0,-1,1],
    "team2_history":[1,1,1,-1,0],
    "team1_recent":[1,1,0,-1,1],
    "team2_recent":[1,1,0,1,1],

    "team1_player":" Alexis Sánchez ",
    "team2_player":" Kylian Mbappé    "
},

{
    "No":"26",
    "date":"20th December 2021, 19:00 PM",
    "team1":"Norway",
    "team2":"Uruguay",
    "img1":"flag/Norway.png",
    "img2":"flag/Uruguay.png",
    "team1_prob":"35%",
    "team2_prob":"65%",
    "matches":"10",
    "team1_win":"2",
    'team2_win':"5",
    "draw":"3",
    "team1_top":" Jens Petter Hauge    ",
    "team2_top":"Luis Suárez    ",
    "team1_history":[0,0,1,-1,1],
    "team2_history":[1,1,0,-1,0],
    "team1_recent":[1,1,0,-1,1],
    "team2_recent":[1,1,0,1,1],

    "team1_player":" Jens Petter Hauge ",
    "team2_player":" Giorgian de Arrascaeta    "
},

{
    "No":"27",
    "date":"21st December 2021, 19:00 PM",
    "team1":"England",
    "team2":"Argentina",
    "img1":"flag/download.png",
    "img2":"flag/Argentina.png",
    "team1_prob":"49%",
    "team2_prob":"51%",
    "matches":"18",
    "team1_win":"8",
    'team2_win':"10",
    "draw":"3",
    "team1_top":" David Beckham  ",
    "team2_top":"Lionel Messi   ",
    "team1_history":[0,0,1,-1,1],
    "team2_history":[1,1,0,-1,0],
    "team1_recent":[1,1,0,-1,1],
    "team2_recent":[1,1,0,1,1],

    "team1_player":" Harry Kane ",
    "team2_player":" Lionel Messi  "
},

{
    "No":"28",
    "date":"22nd December 2021, 19:00 PM",
    "team1":"Italy",
    "team2":"France",
    "img1":"flag/Italy.png",
    "img2":"flag/France.png",
    "team1_prob":"52%",
    "team2_prob":"48%",
    "matches":"25",
    "team1_win":"13",
    'team2_win':"10",
    "draw":"2",
    "team1_top":" Lorenzo Insigne    ",
    "team2_top":"Zinedine Zidane    ",
    "team1_history":[1,0,1,-1,1],
    "team2_history":[0,1,0,-1,0],
    "team1_recent":[1,1,0,-1,1],
    "team2_recent":[1,1,0,1,1],

    "team1_player":" Marco Verratti    ",
    "team2_player":" Antoine Griezmann    "
},
]
const summary=[
    {
    "no":"3",
    "date":"20th August 2021 at 19:00 PM",
    "team1":"France",
    "team2":"Netharland",
    "team1_flag":"../flag/France.png",
    "team2_flag":"../flag/Netharland.png",
    "team1_score":"1",
    "team2_score":"2",
    "team1_goal":["ABC 15'"],
    "team2_goal":["xyz 18'","pqr 56'"],
    "team1_short":"15",
    "team2_short":"20",
    "team1_target":"8",
    "team2_target":"5",
    "team1_poss":"60%",
    "team2_poss":"40%",
    "team1_pass":"426",
    "team2_pass":"300",
    "team1_acc":"80%",
    "team2_acc":"81%",
    "team1_foul":"5",
    "team2_foul":"3",
    "team1_yelllow":"0",
    "team2_yellow":"0",
    "team1_red":"0",
    "team2_red":"0",
    "team1_offside":"2",
    "team2_offside":"0",
    "team1_corner":"4",
    "team2__corner":"6"
},
{
    "no":"4",
    "date":"21st August 2021 at 19:00 PM",

    "team1":"Belgium",
    "team2":"Argentina",
    "team1_flag":"../flag/Belgium.png",
    "team2_flag":"../flag/Argentina.jpg",
    "team1_score":"0",
    "team2_score":"0",
    "team1_goal":[],
    "team2_goal":[],
    "team1_short":"15",
    "team2_short":"20",
    "team1_target":"8",
    "team2_target":"5",
    "team1_poss":"60%",
    "team2_poss":"40%",
    "team1_pass":"426",
    "team2_pass":"300",
    "team1_acc":"80%",
    "team2_acc":"81%",
    "team1_foul":"5",
    "team2_foul":"3",
    "team1_yelllow":"0",
    "team2_yellow":"0",
    "team1_red":"0",
    "team2_red":"0",
    "team1_offside":"2",
    "team2_offside":"0",
    "team1_corner":"4",
    "team2__corner":"6"
},
{
    "no":"5",
    "date":"22nd August 2021 at 19:00 PM",

    "team1":"Norway",
    "team2":"Chile",
    "team1_flag":"../flag/Norway.png",
    "team2_flag":"../flag/Chile.png",
    "team1_score":"1",
    "team2_score":"0",
    "team1_goal":["ABC 15'"],
    "team2_goal":[],
    "team1_short":"15",
    "team2_short":"20",
    "team1_target":"8",
    "team2_target":"5",
    "team1_poss":"60%",
    "team2_poss":"40%",
    "team1_pass":"426",
    "team2_pass":"300",
    "team1_acc":"80%",
    "team2_acc":"81%",
    "team1_foul":"5",
    "team2_foul":"3",
    "team1_yelllow":"0",
    "team2_yellow":"0",
    "team1_red":"0",
    "team2_red":"0",
    "team1_offside":"2",
    "team2_offside":"0",
    "team1_corner":"4",
    "team2__corner":"6"
},
{
    "no":"6",
    "date":"23rd August 2021 at 19:00 PM",

    "team1":"Germany",
    "team2":"Uruguay ",
    "team1_flag":"../flag/Germany.png",
    "team2_flag":"../flag/Uruguay.png",
    "team1_score":"2",
    "team2_score":"1",
    "team1_goal":["ABC 15'","LMN 65'"],
    "team2_goal":["xyz 18'"],
    "team1_short":"15",
    "team2_short":"20",
    "team1_target":"8",
    "team2_target":"5",
    "team1_poss":"60%",
    "team2_poss":"40%",
    "team1_pass":"426",
    "team2_pass":"300",
    "team1_acc":"80%",
    "team2_acc":"81%",
    "team1_foul":"5",
    "team2_foul":"3",
    "team1_yelllow":"0",
    "team2_yellow":"0",
    "team1_red":"0",
    "team2_red":"0",
    "team1_offside":"2",
    "team2_offside":"0",
    "team1_corner":"4",
    "team2__corner":"6"
},
{
    "no":"7",
    "date":"24th August 2021 at 19:00 PM",

    "team1":"England",
    "team2":"Netharland",
    "team1_flag":"../flag/download.png",
    "team2_flag":"../flag/Netharland.png",
    "team1_score":"3",
    "team2_score":"3",
    "team1_goal":["ABC 15' 26' 75'",],
    "team2_goal":["xyz 18'","pqr 56'","asd 90+2'"],
    "team1_short":"15",
    "team2_short":"20",
    "team1_target":"8",
    "team2_target":"5",
    "team1_poss":"60%",
    "team2_poss":"40%",
    "team1_pass":"426",
    "team2_pass":"300",
    "team1_acc":"80%",
    "team2_acc":"81%",
    "team1_foul":"5",
    "team2_foul":"3",
    "team1_yelllow":"0",
    "team2_yellow":"0",
    "team1_red":"0",
    "team2_red":"0",
    "team1_offside":"2",
    "team2_offside":"0",
    "team1_corner":"4",
    "team2__corner":"6"
},
{
    "no":"8",
    "date":"25th August 2021 at 19:00 PM",

    "team1":"Chile ",
    "team2":"Italy ",
    "team1_flag":"../flag/Chile.png",
    "team2_flag":"../flag/Italy.png",
    "team1_score":"2",
    "team2_score":"0",
    "team1_goal":["ABC 15'","dfg 30'"],
    "team2_goal":[],
    "team1_short":"15",
    "team2_short":"20",
    "team1_target":"8",
    "team2_target":"5",
    "team1_poss":"60%",
    "team2_poss":"40%",
    "team1_pass":"426",
    "team2_pass":"300",
    "team1_acc":"80%",
    "team2_acc":"81%",
    "team1_foul":"5",
    "team2_foul":"3",
    "team1_yelllow":"0",
    "team2_yellow":"0",
    "team1_red":"0",
    "team2_red":"0",
    "team1_offside":"2",
    "team2_offside":"0",
    "team1_corner":"4",
    "team2__corner":"6"
},
{
    "no":"9",
    "date":"26th August 2021 at 19:00 PM",

    "team1":"Norway",
    "team2":"Brazil",
    "team1_flag":"../flag/Norway.png",
    "team2_flag":"../flag/Brazil.png",
    "team1_score":"0",
    "team2_score":"1",
    "team1_goal":[],
    "team2_goal":["pqr 56'"],
    "team1_short":"15",
    "team2_short":"20",
    "team1_target":"8",
    "team2_target":"5",
    "team1_poss":"60%",
    "team2_poss":"40%",
    "team1_pass":"426",
    "team2_pass":"300",
    "team1_acc":"80%",
    "team2_acc":"81%",
    "team1_foul":"5",
    "team2_foul":"3",
    "team1_yelllow":"0",
    "team2_yellow":"0",
    "team1_red":"0",
    "team2_red":"0",
    "team1_offside":"2",
    "team2_offside":"0",
    "team1_corner":"4",
    "team2__corner":"6"
},
{
    "no":"10",
    "date":"27th August 2021 at 19:00 PM",

    "team1":"England",
    "team2":"Belgium",
    "team1_flag":"../flag/download.png",
    "team2_flag":"../flag/Belgium.png",
    "team1_score":"2",
    "team2_score":"0",
    "team1_goal":["ABC 15' 45'"],
    "team2_goal":[],
    "team1_short":"15",
    "team2_short":"20",
    "team1_target":"8",
    "team2_target":"5",
    "team1_poss":"60%",
    "team2_poss":"40%",
    "team1_pass":"426",
    "team2_pass":"300",
    "team1_acc":"80%",
    "team2_acc":"81%",
    "team1_foul":"5",
    "team2_foul":"3",
    "team1_yelllow":"0",
    "team2_yellow":"0",
    "team1_red":"0",
    "team2_red":"0",
    "team1_offside":"2",
    "team2_offside":"0",
    "team1_corner":"4",
    "team2__corner":"6"
}



]
const player=[
    {
        "id":"1",
        "name":"Diego Maradona",
        "img":"../players/Maradona.jfif",
        "full name":"Diego Armando Maradona",
        "born":"1960",
        "died":"2020",
        "age":null,
        "country":"Argentinian",
        "height":"1.65m",
        "foot":"Left",
        "pos":"Midfield",
        "number":"10",
        "match":"100",
        "goal":"100",
        "club":["Argentinos Juniors","Boca Juniors","Barcelona","Napoli","Sevilla"],
        "league":["Primera División","Primera División","La Liga","Serie A","La Liga"],
        "leg_match":["167","40","58","259","28"],
        "leg_goal":["115","28","28","115","8"],
        "photo":["../trophy/WorldCup.jpg","../trophy/euro.jfif","../trophy/copa.jpg","../trophy/super.png","../trophy/italy.png"],
        "trophyText":["World Cup 1986","UEFA EURO 1989","Copa Del Rey 1983","Spainish Super Cup 1983","Italy Cup 1987"]
        
    },
    
    {
        "id":"2",
        "name":"Daniel Passarella",
        "img":"../players/passarella.jfif",
        "full name":"Daniel Alberto Passarella",
        "born":"1953",
        "died":null,
        "age":"68",
        "country":"Argentinian",
        "height":"1.73m",
        "foot":"right",
        "pos":"Centre back, sweeper",
        "number":"8",
        "match":"100",
        "goal":"100",
        "club":["Sarmiento","River Plate","	Fiorentina","	Internazionale	","	River Plate"],
        "league":["Primera División","Primera División","Serie A","Serie A","Primera División"],
        "leg_match":["36","226","109","44","32"],
        "leg_goal":["9","90","26","9","9"],
        "photo":["../trophy/argentina.png","../trophy/argentina.png","../trophy/argentina.png","../trophy/argentina.png","../trophy/argentina.png"],
        "trophyText":["Primera División 1945","Primera División 1946","Primera División 1947","La Liga 1957","La Liga 1962"]
        
    },
    {
        "id":"3",
        "name":"Javier Zanetti",
        "img":"../players/javier.jpg",
        "full name":"Javier Adelmar Zanetti",
        "born":"1973",
        "died":null,
        "age":48,
        "country":"Argentinian",
        "height":"1.78m",
        "foot":"Left",
        "pos":"Midfielder, Defender",
        "number":"4",
        "match":"145",
        "goal":"15",
        "club":["Talleres","Banfield","Inter Milan","--","--"],
        "league":["Primera División","Primera División","Seria A","--","--"],
        "leg_match":["33","66","615","",""],
        "leg_goal":["1","4","12","",""],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
        "trophyText":["Seria A 2005","Seria A 2007","UEFA  Leaugue 2009 ","FIFA Club World Cup: 2010","PAN America Games 2010"]
        
    },
    {
        "id":"4",
        "name":"Alfredo Stéfano",
        "img":"../players/alferdo.jpg",
        "full name":"Alfredo Di Stéfano",
        "born":"1926",
        "died":"2014",
        "age":null,
        "country":"Argentinian",
        "height":"1.78m",
        "foot":"Left",
        "pos":"Forward",
        "number":"10",
        "match":"6",
        "goal":"6",
        "club":["River Plate"," Huracán","Millonarios","Real Madrid","Espanyol"],
        "league":["Primera División","Primera División","La Liga","Serie A","La Liga"],
        "leg_match":["66","25","101","282","47"],
        "leg_goal":["49","10","90","216","11"],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["Primera División 1945","Primera División 1946","La Liga 1953","La Liga 1960","La Liga 1966"]
        
    },
    
    {
        "id":"5",
        "name":"Tostão",
        "img":"../players/Tostao.jpg",
        "full name":"Eduardo Gonçalves de Andrade",
        "born":"1947",
        "died":null,
        "age":"74",
        "country":"Brazilian",
        "height":"1.72m",
        "foot":"Right",
        "pos":"Forward",
        "number":"10",
        "match":"97",
        "goal":"3",
        "club":["América Mineiro"," Cruzeiro","	Vasco da Gama"],
        "league":["Primera División","Primera División","La Liga","Serie A","La Liga"],
        "leg_match":["26","378","45"],
        "leg_goal":["16","249","6"],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["Brazilian División ","Brazilian División","Brazilian División","Brazilian División","Brazilian División"]
        
    },

    {
        "id":"6",
        "name":"Pele",
        "img":"../players/pele.jfif",
        "full name":"Edson Arantes do Nascimento",
        "born":"1940",
        "died":null,
        "age":"80",
        "country":"Brazilian",
        "height":"1.73m",
        "foot":"Right",
        "pos":"Forward",
        "number":"10",
        "match":"92",
        "goal":"77",
        "club":["Santos"," 	New York Cosmos","..","..",".."],
        "league":["Primera División","Primera División","--","--","--"],
        "leg_match":["26","378","..","..",".."],
        "leg_goal":["16","249","..","..",".."],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["FIFA World Cup 1958","FIFA World Cup 1962","FIFA World Cup 1970","Taça do Atlântico 1960","Roca Cup 1957"]
        
    },
    {
        "id":"7",
        "name":"Ronaldinho",
        "img":"../players/ronaldinho.jfif",
        "full name":"Ronaldo de Assis Moreira",
        "born":"1980",
        "died":null,
        "age":"41",
        "country":"Brazilian",
        "height":"1.82m",
        "foot":"Right",
        "pos":"Forward",
        "number":"10",
        "match":"92",
        "goal":"77",
        "club":["Grêmio","Paris Saint-Germain","Barcelona","AC Milan","Atlético Mineiro"],
        "league":["Brazilian División","League 1","La Liga","Seria A","Brazilian División"],
        "leg_match":["88","55","145","76","58"],
        "leg_goal":["47","17","70","20","20"],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["La Liga 2004","UEFA Champion 2005","Seria A 2010","Taça do Atlântico 2001","Roca Cup 2008"]
        
    },
    {
        "id":"8",
        "name":"Sócrates",
        "img":"../players/socretes.jfif",
        "full name":"Sócrates Brasileiro Sampaio de Souza Vieira de Oliveira",
        "born":"1954",
        "died":"2011",
        "age":null,
        "country":"Brazilian",
        "height":"1.92m",
        "foot":"Right",
        "pos":"Midfielder",
        "number":"9",
        "match":"60",
        "goal":"22",
        "club":["Botafogo-SP","	Corinthians","	Fiorentina","Flamengo","Santos"],
        "league":["Brazilian División","Brazilian División","Seria A","Brazilian División","Brazilian División"],
        "leg_match":["99","135","25","12","25"],
        "leg_goal":["53","74","6","3","7"],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["Torneio Vicente Feola: 1976","Taça Rio: 1986","Campeonato Paulista 1979","Campeonato Paulista 1982","Campeonato Paulista 1983"]
        
    },
    {
        "id":"9",
        "name":"Matthias Sammer",
        "img":"../players/sammer.jfif",
        "full name":"Matthias Sammer",
        "born":"1967",
        "died":null,
        "age":54,
        "country":"German",
        "height":"1.81m",
        "foot":"Right",
        "pos":"Defender",
        "number":"3",
        "match":"74",
        "goal":"14",
        "club":["Dynamo Dresden","VfB Stuttgart","Inter Milan","Borussia Dortmund","..."],
        "league":["Bundesliga","Bundesliga","Seria A","Bundesliga",".."],
        "leg_match":["102","63","11","115",".."],
        "leg_goal":["39","20","4","21",".."],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["Bundesliga 1991","US Cup 1993","Ballon d'Or 1996","UEFA European Championship 1996","Footballer of the Year 1995"]
        
    },
    {
        "id":"10",
        "name":"Bastian Schweinsteiger",
        "img":"../players/sch.jfif",
        "full name":"Bastian Schweinsteiger",
        "born":"1984",
        "died":null,
        "age":37,
        "country":"German",
        "height":"1.83m",
        "foot":"Right",
        "pos":"Midfielder",
        "number":"31",
        "match":"121",
        "goal":"24",
        "club":["Bayern Munich","Manchester United","Chicago Fire","..","..."],
        "league":["Bundesliga","EPL","American League","...",".."],
        "leg_match":["342","18","85","..",".."],
        "leg_goal":["45","1","18","..",".."],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["Bundesliga 2002","Bundesliga 2007","Bundesliga 2014","UEFA European Championship 2017","World Cup 2014"]
        
    },
    {
        "id":"11",
        "name":"Miroslav Klose        ",
        "img":"../players/klose.jpg",
        "full name":"Miroslav Josef Klose",
        "born":"1978",
        "died":null,
        "age":43,
        "country":"German",
        "height":"1.83m",
        "foot":"Right",
        "pos":"Forward",
        "number":"11",
        "match":"137",
        "goal":"71",
        "club":["Bayern Munich","FC 08 Homburg","FC Kaiserslautern","Lazio","..."],
        "league":["Bundesliga","Bundesliga","Bundesliga","Seria A",".."],
        "leg_match":["98","18","120","139",".."],
        "leg_goal":["44","1","44","54",".."],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["Bundesliga 2008","Bundesliga 2009","Coppa Italia 2012","DFB-Supercup 2010","World Cup 2014"]
        
    },
    {
        "id":"12",
        "name":"Gerd Müller",
        "img":"../players/muller.jpg",
        "full name":"Gerhard Gerd Müller",
        "born":"1945",
        "died":"2021",
        "age":null,
        "country":"German",
        "height":"1.76m",
        "foot":"Left",
        "pos":"Forward",
        "number":"9",
        "match":"62",
        "goal":"68",
        "club":["1861 Nördlingen","	Bayern Munich","Fort Lauderdale Strikers","...","..."],
        "league":["Bundesliga","Bundesliga","Americaan League","..",".."],
        "leg_match":["31","453","71","...",".."],
        "leg_goal":["51","398","38","...",".."],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["Bundesliga 1968","Bundesliga 1972","European Cup 1973","Intercontinental Cup 1976","World Cup 1974"]
        
    },
    {
        "id":"13",
        "name":"Giuseppe Meazza",
        "img":"../players/meazza.jfif",
        "full name":"Giuseppe Peppino Meazza",
        "born":"1910",
        "died":"1979",
        "age":null,
        "country":"Italian",
        "height":"1.69m",
        "foot":"Left",
        "pos":"Forward",
        "number":"7",
        "match":"53",
        "goal":"33",
        "club":["Internazionale","Milan","Juventus","Varese","Atalanta"],
        "league":["Seria A","Seria A","Seria A","Seria A","Seria A"],
        "leg_match":["348","37","27","20","14"],
        "leg_goal":["240","9","10","9","2"],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["Seria A 1929","Seria A 1937","Seria A 1940","World Cup 1934","World Cup 1938"]
        
    },
    {
        "id":"14",
        "name":"Paolo Maldini",
        "img":"../players/maldini.jfif",
        "full name":"Paolo Cesare Maldini",
        "born":"1968",
        "died":null,
        "age":"53",
        "country":"Italian",
        "height":"1.86m",
        "foot":"Left",
        "pos":"Defender",
        "number":"3",
        "match":"126",
        "goal":"7",
        "club":["Milan","..","..","..",".."],
        "league":["Seria A","...","...","...","..."],
        "leg_match":["647","...","...","...","..."],
        "leg_goal":["29","...","...","...","..."],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["Seria A 1987","Seria A 1993","Bravo Award: 1989","Ballon d'Or:2003","World Cup 2006"]
        
    },
    {
        "id":"15",
        "name":"Roberto Baggio",
        "img":"../players/roberto.jpg",
        "full name":"Roberto Baggio Cavaliere",
        "born":"1967",
        "died":null,
        "age":"54",
        "country":"Italian",
        "height":"1.74m",
        "foot":"right",
        "pos":"Forward/Midfielder",
        "number":"10",
        "match":"56",
        "goal":"27",
        "club":["Vicenza","Fiorentina","Juventus","AC Milan","Bologna"],
        "league":["Seria A","Seria A","Seria A","Seria A","Seria A"],
        "leg_match":["36","95","141","51","30"],
        "leg_goal":["13","39","78","12","22"],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["Seria A 1994","Seria A 1995","UEFA Cup: 1993","Onze d'Or 1993","Bravo Award 1990"]
        
    },
    {
        "id":"16",
        "name":"Andrea Pirlo",
        "img":"../players/pirlo.jfif",
        "full name":"Andrea Pirlo",
        "born":"1979",
        "died":null,
        "age":"42",
        "country":"Italian",
        "height":"1.77m",
        "foot":"right",
        "pos":"Midfielder",
        "number":"21",
        "match":"116",
        "goal":"13",
        "club":["Brescia","Inter Milan","AC Milan","Juventus","	New York City FC"],
        "league":["Seria A","Seria A","Seria A","Seria A","Amrican League"],
        "leg_match":["47","22","284","119","60"],
        "leg_goal":["6","0","32","16","1"],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["Seria A 2003","Seria A 2010","fifa club world cup: 2007","UEFA Super Cup 2007","World cup 2006"]
        
    },
    {
        "id":"17",
        "name":"Lionel Messi",
        "img":"../players/messi.jfif",
        "full name":"Lionel Andrés Messi",
        "born":"1987",
        "died":null,
        "age":"34",
        "country":"Argentanian",
        "height":"1.69m",
        "foot":"left",
        "pos":"Forward",
        "number":"10",
        "match":"154",
        "goal":"79",
        "club":["Barcelona","Paris Saint-Germain","...","...","	..."],
        "league":["La Liga","League 1","...","...","..."],
        "leg_match":["520","4","...","...","..."],
        "leg_goal":["474","1","...","...","..."],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["La Liga 2005","La Liga 2010","Copa America 2021","Ballon d'Or 2015","Ballon d'Or 2019"]
        
    },
    {
        "id":"18",
        "name":"Cristiano Ronaldo        ",
        "img":"../players/cristiano.jpg",
        "full name":"Cristiano Ronaldo dos Santos ",
        "born":"1985",
        "died":null,
        "age":"36",
        "country":"Portuguese",
        "height":"1.87m",
        "foot":"right",
        "pos":"Forward",
        "number":"7",
        "match":"180",
        "goal":"111",
        "club":["Sporting CP","Manchester United","	Real Madrid","Juventus","Manchester United"],
        "league":["Primeira Liga","EPL","La Liga","Seria A","EPL"],
        "leg_match":["25","196","292","98","4"],
        "leg_goal":["3","84","311","81","3"],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["La Liga 2011","La Liga 2016","Seria A 2018","UEFA European Championship 2016","Ballon d'Or 2017"]
        
    },
    {
        "id":"19",
        "name":"Robert Lewandowski        ",
        "img":"../players/lewandoski.jfif",
        "full name":"Robert Lewandowski ",
        "born":"1988",
        "died":null,
        "age":"33",
        "country":"Polish",
        "height":"1.85m",
        "foot":"right",
        "pos":"Forward",
        "number":"9",
        "match":"125",
        "goal":"72",
        "club":["Legia Warsaw II","	Znicz Pruszków","Lech Poznań","Borussia Dortmund","Bayern Munich"],
        "league":["Polish League","Polish League","Polish League","Bundesliga","Bundesliga"],
        "leg_match":["12","59","58","131","226"],
        "leg_goal":["2","36","32","74","210"],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["Bundesliga 2014","Bundesliga 2016","Bundesliga 2020","UEFA Champions League 2019","FIFA Club World Cup: 2020"]
        
    },
    {
        "id":"20",
        "name":"Luka Modrić",
        "img":"../players/modric.jpg",
        "full name":"Luka Modrić",
        "born":"1985",
        "died":null,
        "age":"36",
        "country":"Croatian",
        "height":"1.72m",
        "foot":"right",
        "pos":"Midfielder",
        "number":"10",
        "match":"142",
        "goal":"18",
        "club":["Dinamo Zagreb","Tottenham Hotspur","Real Madrid","...","..."],
        "league":["Crotian League","EPL","La Liga","..",".."],
        "leg_match":["94","127","271","..",".."],
        "leg_goal":["26","13","20","..",".."],
        "photo":["../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif","../trophy/trophy.jfif"],
       
        "trophyText":["La Liga: 2016","Copa del Rey 2013","UEFA Super Cup: 2014","Ballon d'Or: 2018","Croatian Super Cup: 2006"]
        
    },

]

    


module.exports=summary 