services:
  server:
    build: .
    ports:
      - '3000:3000'
    networks:
      - soccer
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    networks:
      - soccer
    volumes:
      - /my/own/datadir:/data/db
    
  
networks:
  soccer:
    driver: bridge